
name: valint dev

on: 
    push:
    workflow_dispatch:
    
env:
     SCRIBE_URL: "https://airflow.dev.scribesecurity.com"
     SCRIBE_LOGIN_URL: "https://scribe-hub-dev.us.auth0.com"
     SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"
     IMAGE_NAME: adam-image
     IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
     PRODUCT_NAME: 'Adam_Product_2'
     APP_NAME: adam-app
     APP_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    steps:
  
      - name: create file and Docker
        run: | 
          echo `date` > tmp.txt
          echo "FROM scratch" > Dockerfile
          echo "COPY . ." >> Dockerfile
          docker build -t date:latest .

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          repository: mongo-express/mongo-express
          ref: refs/tags/v1.0.0-alpha.4
          path: mongo-express-scm

      - name: Valint Git
        uses: scribe-security/action-bom@master
        with:
          target: git:.
          format: attest
          scribe-enable: true
          product-key: $PRODUCT_NAME
          scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          app-name: $APP_NAME
          app-version: $APP_VERSION

      - name: Valint Git Verify
        uses: scribe-security/action-verify@master
        with:
          target: git:.
          format: attest
          scribe-enable: true
          product-key: $PRODUCT_NAME
          scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          app-name: $APP_NAME
          app-version: $APP_VERSION

       
